### ISSUE TITLE
Missing appsettings.json

### ISSUE THREAD

**Issue by adrianh-za** [claudiobernasconi/SerilogDemo#1]
Hi

The appsettings.json is missing from the repo.

**Comment by ghost** [comment]
Use this:

"Logging": {
  "LogLevel": {
    "Default": "Information",
    "Microsoft.AspNetCore": "Warning"
  }
},
"Serilog": {
  "Using": [ "Serilog.Sinks.File" ],
  "MinimumLevel": {
    "Default": "Information"
  },
  "WriteTo": [
    {
      "Name": "File",
      "Args": {
        "path": "../logs/webapi-.log",
        "rollingInterval": "Day",
        "outputTemplate":  "[{Timestamp:yyyy-MM-dd HH:mm:ss:fff zzz} {CorrelationId} {Level:u3}] {UserName} {Message:lj}{NewLine}{Exception}"
      }
    }
  ]
}

**Comment by claudiobernasconi** [comment]
Sorry, I just added mine. 

https://github.com/claudiobernasconi/SerilogDemo/blob/main/SerilogDemo/appsettings.json

However, thanks @Petr-Brozek. Your config should also work.
